---
# pt driver prepare
- name: add virtual box repository
  shell:
      echo "deb http://download.virtualbox.org/virtualbox/debian wheezy contrib" >> /etc/apt/sources.list
  tags: virtualbox

- name: add oracle key
  shell:
      wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -
  tags: virtualbox

- name: be sure virtualbox is installed
  apt: name=virtualbox-4.3 update_cache=yes
  tags: virtualbox

- name: be sure curl is installed
  apt: name=curl state=present
  tags: vagrant

- name: download vagrant deb package
  command:
      curl -LO https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3_x86_64.deb
      chdir=/tmp
      creates=vagrant_1.6.3_x86_64.deb
  tags: vagrant

- name: install vagrant
  command:
      dpkg --install vagrant_1.6.3_x86_64.deb
      chdir=/tmp
  tags: vagrant

